#calculating mean

#manual calculating

In [3]:
population=[150,160,170,165,155]
sample=[150,170,165]
pop_mean=sum(population)/len(population)
print(pop_mean)
sample_mean=sum(sample)/len(sample)
print(sample_mean)

160.0
161.66666666666666

#by using numpy

In [6]:
import numpy as np
data=[85,90,87,92,88]
mean=np.mean(data)
print(mean)

88.4

#by using statistics

In [7]:
import statistics as stats

In [8]:
var=[10,20,30,40,50]
mean_stats=stats.mean(var)
print(mean_stats)

30

#from dataset

In [11]:
import seaborn as sns
import numpy as np
iris=sns.load_dataset('iris')
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [12]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [14]:
mean_sepal_length=np.mean(iris['sepal_length'])
print(mean_sepal_length)

5.843333333333334

#median

#method_1, with numpy

In [15]:
data=[20,22,24,26,28,100]
median=np.median(data)
print(median)

25.0

#method_2-by busing statistics

In [17]:
import statistics as stats
data=[1,41,54,5,51,56]
median_stats=stats.median(data)
print(median_stats)

46.0

#with the help of pandas

In [24]:
import pandas as pd
df=pd.DataFrame({'values':[20,22,24,26,28,100]})
print(df)
median_pandas=df['values'].median()
print(median_pandas)

   values
0      20
1      22
2      24
3      26
4      28
5     100
25.0

#data set

In [ ]:
import seaborn as sns
import numpy as np
iris=sns.load_dataset('iris')
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [25]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [27]:
np_median=np.median(iris['sepal_length'])
print(np_median)

5.8

#mode

#method-1 with the help of statistics

In [29]:
import statistics as stats
data=[85,90,90,95,85,85,96,80]
mode=stats.mode(data)
print(mode)

85

In [2]:
import statistics as stats
data=[85,90,90,90,95,85,85,96,80]
mode=stats.mode(data)
print(mode)

85

#with the help of scipy library

In [3]:
from scipy import stats

In [4]:
data=[85,90,90,95,85,80,85,91,80]
mode =stats.mode(data)
print(mode)

ModeResult(mode=np.int64(85), count=np.int64(3))

#varience

#using numpy

In [11]:
import numpy as np
data=[2,4,4,5,6,7,8,9]
sample_varience=np.var(data, ddof=1)
print(sample_varience)
pop_varience=np.var(data,ddof=0)
print(pop_varience)

5.410714285714286
4.734375

#using pandas

In [17]:
import pandas as pd
data=[2,5,6,6,7,8,5,4,9,14,2,10]
Series=pd.Series(data)
print(Series)
sample_vrience=Series.var()
print(sample_vrience)
pop_varience=Series.var(ddof=0)
print(pop_varience)

0      2
1      5
2      6
3      6
4      7
5      8
6      5
7      4
8      9
9     14
10     2
11    10
dtype: int64
11.727272727272727
10.75

#using scipy

In [22]:
from scipy import stats
data=[7,8,9,1,8,5,2,6,4]
sample_varience=stats.tvar(data)
print(sample_varience)
pop_varience=stats.tvar(data, ddof=0)
print(pop_varience)

7.777777777777778
6.91358024691358

#standard deviation

#using numpy

In [3]:
import numpy as np
data=[60,65,70,75,80]
sample_std=np.std(data,ddof=1)
print(sample_std)
pop_std=np.std(data,ddof=0)
print(pop_std)

7.905694150420948
7.0710678118654755

#using pandas as pd

In [8]:
import pandas as pd
data=[2,5,6,67,8,5,4,9,14,2,10]
Series=pd.Series(data)
print(Series)
sample_std=Series.std()
print(sample_std)
pop_std=Series.std(ddof=0)
print(pop_std)

0      2
1      5
2      6
3     67
4      8
5      5
6      4
7      9
8     14
9      2
10    10
dtype: int64
18.5903200617956
17.725174701023914

#using scipy library

In [11]:
from scipy import stats
import math
sample_std=math.sqrt(stats.tvar(data))
print(sample_std)
pop_std=math.sqrt(stats.tvar(data,ddof=0))
print(pop_std)

18.5903200617956
17.725174701023914